paths:
  excel: "C:/Users/yongh/Downloads/FinanceTracker/Personal Portfolio.xlsm"
  watch_dir: "data"
  log: "logs/app.log"

database:
  driver: "OCBC Driver 17 for SQL Server"
  server: "YH-PC"
  database: "Finance"
